-- 30 Özgün Blog Yazısı Gerçek Görseller İle Seed SQL
INSERT INTO articles (title, slug, excerpt, content, cover_image, city_slug, meta_title, meta_description, is_published, published_at, created_at, updated_at)
VALUES
(
  'İstanbul''un En Etkileyici 10 Tarihi Müzesi ve Gezi Rehberi',
  'istanbul-en-etkileyici-tarihi-muzeler',
  'Tarih boyunca üç büyük imparatorluğa başkentlik yapan İstanbul''un mutlaka görülmesi gereken en görkemli 10 tarihi müzesi ve detaylı gezi rehberi.',
  '# İstanbul''un En Etkileyici 10 Tarihi Müzesi...',
  'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?q=80&w=1200&auto=format&fit=crop',
  'istanbul',
  'İstanbul''un En Etkileyici 10 Tarihi Müzesi | Seni de Bekleriz',
  'İstanbul''da gezilmesi gereken en önemli 10 tarihi müze. Ayasofya, Topkapı Sarayı, İstanbul Arkeoloji Müzeleri.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Göbeklitepe: Tarihin Sıfır Noktası ve İnsanlık Tarihini Değiştiren Keşif',
  'gobeklitepe-tarihin-sifir-noktasi',
  'Şanlıurfa''da yer alan ve günümüzden 12.000 yıl öncesine tarihlenen Göbeklitepe.',
  '# Göbeklitepe: Tarihin Sıfır Noktası...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/G%C3%B6bekli_Tepe%2C_%C5%9Eanl%C4%B1urfa.jpg/1200px-G%C3%B6bekli_Tepe%2C_%C5%9Eanl%C4%B1urfa.jpg',
  'sanliurfa',
  'Göbeklitepe: Tarihin Sıfır Noktası Şanlıurfa | Seni de Bekleriz',
  'İnsanlık tarihinin bilinen en eski tapınak kompleksi Göbeklitepe.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Efes Antik Kenti: İyonya''nın Görkemli Başkenti ve Celsus Kütüphanesi',
  'efes-antik-kenti-ve-celsus-kutuphanesi',
  'İzmir''in Selçuk ilçesinde yer alan UNESCO Dünya Mirası Efes Antik Kenti.',
  '# Efes Antik Kenti: İyonya''nın Görkemli Başkenti...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Library_of_Celsus_in_Ephesus.jpg/1200px-Library_of_Celsus_in_Ephesus.jpg',
  'izmir',
  'Efes Antik Kenti ve Celsus Kütüphanesi Rehberi | Seni de Bekleriz',
  'İzmir Efes Antik Kenti nerede, Celsus Kütüphanesi rehberi.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Sumela Manastırı: Karadeniz''in Kayalara Oyulmuş İnanç Mabedi',
  'sumela-manastiri-trabzon-rehberi',
  'Trabzon Maçka''da Karadağ''ın sarp kayalıklarına inşa edilmiş 1600 yıllık tarihi Meryem Ana Manastırı.',
  '# Sumela Manastırı: Kayalardaki Asırlık Miras...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Sumela_Monastery_Trabzon_Turkey.jpg/1200px-Sumela_Monastery_Trabzon_Turkey.jpg',
  'trabzon',
  'Sümela Manastırı Trabzon Gezi Rehberi | Seni de Bekleriz',
  'Trabzon Sümela Manastırı nerede, tarihi ve freskleri.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Nemrut Dağı Dev Heykelleri: Kommagene Krallığı''nın Gökyüzü Tapınağı',
  'nemrut-dagi-dev-heykelleri-adiyaman',
  'Adıyaman''da 2.150 metre yükseklikte Kral I. Antiochos tarafından yaptırılan dev tanrı heykelleri.',
  '# Nemrut Dağı Dev Heykelleri...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Mount_Nemrut_heads.jpg/1200px-Mount_Nemrut_heads.jpg',
  'adiyaman',
  'Nemrut Dağı Dev Heykelleri Adıyaman | Seni de Bekleriz',
  'Nemrut Dağı heybetli heykelleri ve Kommagene tümülüsü.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Troya Antik Kenti: Efsaneden Gerçeğe Çanakkale''nin Tarihi Mirası',
  'troya-antik-kenti-canakkale',
  'Homeros''un İlyada Destanı''na konu olan Çanakkale Troya Antik Kenti.',
  '# Troya Antik Kenti: Destanların Doğduğu Yer...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Troy_Wooden_Horse.jpg/1200px-Troy_Wooden_Horse.jpg',
  'canakkale',
  'Troya Antik Kenti ve Troya Müzesi Çanakkale | Seni de Bekleriz',
  'Çanakkale Troya Antik Kenti tarihi ve Tahta Atı.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Çatalhöyük Neolitik Kenti: İnsanlığın İlk Şehirleşme İzleri',
  'catalhoyuk-neolitik-kenti-konya',
  'Konya Çumra''da 9.000 yıl önce kurulan ilk toplu yaşam merkezi Çatalhöyük.',
  '# Çatalhöyük Neolitik Kenti...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/%C3%87atalh%C3%B6y%C3%BCk_South_Area_1.jpg/1200px-%C3%87atalh%C3%B6y%C3%BCk_South_Area_1.jpg',
  'konya',
  'Çatalhöyük Neolitik Kenti Konya | Seni de Bekleriz',
  'Konya Çatalhöyük Neolitik Kenti tarihi.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Anadolu Medeniyetleri Müzesi: Ankara''nın Dünya Çapındaki Tarih Hazinesi',
  'anadolu-medeniyetleri-muzesi-ankara',
  'Ankara Kalesi eteklerindeki tarihi Mahmut Paşa Bedesteni''nde yer alan müze.',
  '# Anadolu Medeniyetleri Müzesi...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Anadolu_Medeniyetleri_M%C3%BCzesi_1.jpg/1200px-Anadolu_Medeniyetleri_M%C3%BCzesi_1.jpg',
  'ankara',
  'Anadolu Medeniyetleri Müzesi Ankara | Seni de Bekleriz',
  'Ankara Anadolu Medeniyetleri Müzesi sergileri.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Gaziantep Zeugma Mozaik Müzesi ve Çingene Kızı''nın Hikayesi',
  'zeugma-mozaik-muzesi-gaziantep',
  'Dünyanın en büyük mozaik müzelerinden biri ve Çingene Kızı mozaiği.',
  '# Gaziantep Zeugma Mozaik Müzesi...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Gypsy_Girl_Mosaic_Zeugma.jpg/1200px-Gypsy_Girl_Mosaic_Zeugma.jpg',
  'gaziantep',
  'Zeugma Mozaik Müzesi Gaziantep | Seni de Bekleriz',
  'Gaziantep Zeugma Mozaik Müzesi ve Çingene Kızı.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Ani Harabeleri: Binbir Kiliseli Kars Antik Kenti',
  'ani-harabeleri-kars-tarihi',
  'Türkiye-Ermenistan sınırında Arpaçay kıyısında yer alan Ani Antik Kenti.',
  '# Ani Harabeleri: Krallar Şehri...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Ani_Katedrali_Kars.jpg/1200px-Ani_Katedrali_Kars.jpg',
  'kars',
  'Ani Harabeleri (Ani Ören Yeri) Kars | Seni de Bekleriz',
  'Kars Ani Ören Yeri tarihi ve Ani Katedrali.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Aspendos Antik Tiyatrosu: Akustiğiyle Büyüleyen Roma Mimarisi',
  'aspendos-antik-tiyatrosu-antalya',
  'Antalya Serik''te bulunun ve günümüze en iyi korunarak ulaşmış Roma tiyatrosu.',
  '# Aspendos Antik Tiyatrosu...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Aspendos_theater_2011.jpg/1200px-Aspendos_theater_2011.jpg',
  'antalya',
  'Aspendos Antik Tiyatrosu Antalya | Seni de Bekleriz',
  'Antalya Aspendos Antik Tiyatrosu nerede, akustiği.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Hattuşaş Antik Kenti: Hitit İmparatorluğu''nun Başkenti',
  'hattusas-antik-kenti-corum-hititler',
  'Çorum Boğazkale''de bulunan Hitit başkenti Hattuşaş.',
  '# Hattuşaş: Hititlerin Güneş Şehri...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Hattusa_Lion_Gate.jpg/1200px-Hattusa_Lion_Gate.jpg',
  'corum',
  'Hattuşaş Antik Kenti Çorum Hitit Mirası | Seni de Bekleriz',
  'Çorum Hattuşaş antik kenti ve Aslanlı Kapı.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Pergamon (Bergama) Antik Kenti: Akropol ve Dünyanın İlk İlaçsız Hastanesi',
  'bergama-pergamon-antik-kenti-izmir',
  'İzmir Bergama''da dik bir tepeye kurulan Pergamon Akropolü.',
  '# Pergamon (Bergama) Antik Kenti...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Acropolis_of_Pergamon.jpg/1200px-Acropolis_of_Pergamon.jpg',
  'izmir',
  'Bergama Pergamon Antik Kenti İzmir | Seni de Bekleriz',
  'İzmir Bergama Pergamon antik kenti.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Safranbolu Evleri: Osmanlı Sivil Mimarisinin Yaşayan Eserleri',
  'safranbolu-evleri-osmanli-mimarisi-karabuk',
  'Karabük Safranbolu''da geleneksel Osmanlı evleri ve tarihi konaklar.',
  '# Safranbolu Evleri: Zamanın Durduğu Şehir...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Safranbolu_traditional_houses.jpg/1200px-Safranbolu_traditional_houses.jpg',
  'karabuk',
  'Safranbolu Evleri ve Tarihi Konaklar Karabük | Seni de Bekleriz',
  'Karabük Safranbolu evleri özellikleri.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'İshak Paşa Sarayı: Ağrı Dağı''nın Eteğinde Bir Osmanlı Masalı',
  'ishak-pasa-sarayi-agri-dogubayazit',
  'Ağrı Doğubayazıt''ta ovaya hakim tepe üzerine kurulu saray.',
  '# İshak Paşa Sarayı: Doğu''daki İhtişam...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Ishak_Pasha_Palace_Do%C4%9Fubeyaz%C4%B1t.jpg/1200px-Ishak_Pasha_Palace_Do%C4%9Fubeyaz%C4%B1t.jpg',
  'agri',
  'İshak Paşa Sarayı Doğubayazıt Ağrı | Seni de Bekleriz',
  'Ağrı Doğubayazıt İshak Paşa Sarayı tarihi.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'İstanbul Arkeoloji Müzeleri: Dünyanın En Zengin Arkeoloji Koleksiyonları',
  'istanbul-arkeoloji-muzeleri-rehberi',
  'Osman Hamdi Bey tarafından kurulan İstanbul Arkeoloji Kompleksi.',
  '# İstanbul Arkeoloji Müzeleri...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Alexander_Sarcophagus_Istanbul.jpg/1200px-Alexander_Sarcophagus_Istanbul.jpg',
  'istanbul',
  'İstanbul Arkeoloji Müzeleri Gezi Rehberi | Seni de Bekleriz',
  'İstanbul Arkeoloji Müzesi''nde sergilenen İskender Lahdi.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Aphrodisias Antik Kenti: Mermer Sanatının ve Heykeltıraşlığın Başkenti',
  'aphrodisias-antik-kenti-aydin',
  'Aydın Karacasu''da bulunan Roma döneminin heykel okulu kenti.',
  '# Aphrodisias Antik Kenti...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Tetrapylon_Aphrodisias.jpg/1200px-Tetrapylon_Aphrodisias.jpg',
  'aydin',
  'Aphrodisias Antik Kenti Aydın | Seni de Bekleriz',
  'Aydın Aphrodisias antik kenti ve Tetrapylon kapısı.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Mardin Taş Evleri ve Tarihi Manastırları: Mezopotamya''nın Masal Şehri',
  'mardin-tas-evleri-ve-tarihi-manastirlari',
  'Sarı kalker taşından yapılan evleri ve manastırlarıyla Mardin.',
  '# Mardin: Gece Gerdanlık, Gündüz Seyranlık...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Old_Mardin_houses.jpg/1200px-Old_Mardin_houses.jpg',
  'mardin',
  'Mardin Taş Evleri ve Manastırları | Seni de Bekleriz',
  'Mardin gezilecek yerler ve Eski Mardin evleri.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Bursa Ulu Camii ve Cumalıkızık: Erken Osmanlı Dönemi Mirası',
  'bursa-ulu-camii-ve-cumalikizik-rehberi',
  'Bursa''da 20 kubbeli Ulu Camii ve 700 yıllık köy Cumalıkızık.',
  '# Bursa Ulu Camii ve Cumalıkızık...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Bursa_Ulu_Camii_2019.jpg/1200px-Bursa_Ulu_Camii_2019.jpg',
  'bursa',
  'Bursa Ulu Camii ve Cumalıkızık Köyü | Seni de Bekleriz',
  'Bursa Ulu Camii ve Cumalıkızık Osmanlı köyü.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Sagalassos Antik Kenti: Toroslar''ın Aşk Şehri ve Antoninler Çeşmesi',
  'sagalassos-antik-kenti-burdur',
  'Burdur Ağlasun''da 1.500 metre yükseklikte Antoninler Çeşmesi ile ünlü kent.',
  '# Sagalassos: Bulutların Üstündeki Antik Kent...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Antoninler_Fountain_Sagalassos.jpg/1200px-Antoninler_Fountain_Sagalassos.jpg',
  'burdur',
  'Sagalassos Antik Kenti Burdur | Seni de Bekleriz',
  'Burdur Sagalassos antik kenti Antoninler Çeşmesi.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Sümela''dan Sonra Karadeniz''in Gizli Hazineleri: Zilkale ve Palovit',
  'rize-zilkale-ve-tarihi-kemer-kopruler',
  'Rize Çamlıhemşin Fırtına Vadisi''nde sarp kayalık üzerindeki Zilkale.',
  '# Rize Zilkale ve Fırtına Vadisi...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Zilkale_Rize_%C3%87aml%C4%B1hem%C5%9Fin.jpg/1200px-Zilkale_Rize_%C3%87aml%C4%B1hem%C5%9Fin.jpg',
  'rize',
  'Rize Zilkale ve Fırtına Vadisi Köprüleri | Seni de Bekleriz',
  'Rize Zilkale nerede, Fırtına Vadisi kemer köprüleri.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Van Kalesi ve Akdamar Kilisesi: Urartu ve Ermeni Mimarisi',
  'van-kalesi-ve-akdamar-kilisesi-van',
  'Van Gölü kıyısındaki Tuşpa (Van Kalesi) ve Akdamar Adası Kilisesi.',
  '# Van Kalesi ve Akdamar Kilisesi...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Akdamar_Church_Van_Lake.jpg/1200px-Akdamar_Church_Van_Lake.jpg',
  'van',
  'Van Kalesi ve Akdamar Kilisesi Gezi Rehberi | Seni de Bekleriz',
  'Van Kalesi Urartu yazıtları, Akdamar Kutsal Haç Kilisesi.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Edirne Selimiye Camii: Mimar Sinan''ın Ustalık Eseri',
  'edirne-selimiye-camii-mimar-sinan',
  'Mimar Sinan''ın ustalık eserim dediği 4 minareli Osmanlı camii.',
  '# Edirne Selimiye Camii: Mimarinin Zirvesi...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Selimiye_Mosque_Edirne.jpg/1200px-Selimiye_Mosque_Edirne.jpg',
  'edirne',
  'Edirne Selimiye Camii Mimar Sinan Mirası | Seni de Bekleriz',
  'Edirne Selimiye Camii mimari özellikleri.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Kilikya Antik Kentleri: Kızkalesi, Cennet-Cehennem Obrukları ve Kanlıdivane',
  'mersin-kizkalesi-cennet-cehennem-obruklari',
  'Mersin kıyılarındaki Kızkalesi ve Cennet-Cehennem obrukları.',
  '# Kilikya''nın Akdeniz Hazineleri...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Kizkalesi_Mersin_Turkey.jpg/1200px-Kizkalesi_Mersin_Turkey.jpg',
  'mersin',
  'Mersin Kızkalesi ve Cennet Cehennem Obrukları | Seni de Bekleriz',
  'Mersin Kızkalesi tarihi, Cennet Cehennem çökükleri.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Aizanoi Antik Kenti: Dünyanın İlk Borsası ve Görkemli Zeus Tapınağı',
  'aizanoi-antik-kenti-kutahya-zeus-tapinagi',
  'Kütahya Çavdarhisar''daki antik Roma kenti Aizanoi ve Zeus Tapınağı.',
  '# Aizanoi: İkinci Efes...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Zeus_Temple_Aizanoi.jpg/1200px-Zeus_Temple_Aizanoi.jpg',
  'kutahya',
  'Aizanoi Antik Kenti Kütahya | Seni de Bekleriz',
  'Kütahya Aizanoi antik kenti Zeus Tapınağı.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Kastamonu Mahmut Bey Camii: Ahşap Çivisiz Mimari Şaheser',
  'kastamonu-mahmut-bey-camii-ahsap-mimari',
  'Kastamonu Kasaba köyünde metal çivi kullanılmadan inşa edilen cami.',
  '# Kastamonu Çivisiz Mahmut Bey Camii...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Mahmut_Bey_Mosque_Kastamonu.jpg/1200px-Mahmut_Bey_Mosque_Kastamonu.jpg',
  'kastamonu',
  'Kastamonu Mahmut Bey Camii Çivisiz Ahşap Miras | Seni de Bekleriz',
  'Kastamonu Çivisiz Mahmut Bey Camii tarihi.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Karasu ve Sinop Tarihi Cezaevi: Anadolu''nun Alcatraz''ı',
  'sinop-tarihi-cezaevi-ve-sinop-kalesi',
  'Tarihi Sinop kaleleri içinde yer alan tarihi cezaevi.',
  '# Sinop Tarihi Cezaevi: Nemli Surların Şiiri...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Sinop_Historical_Prison.jpg/1200px-Sinop_Historical_Prison.jpg',
  'sinop',
  'Sinop Tarihi Cezaevi ve Kalesi | Seni de Bekleriz',
  'Sinop Tarihi Cezaevi gezisi ve Sabahattin Ali hücresi.',
  TRUE, NOW(), NOW(), NOW()
),
(
  'Sivas Divriği Ulu Camii ve Darüşşifası: Taş İşçiliğinin Mucizesi',
  'sivas-divrigi-ulu-camii-ve-darussifikasi',
  'Sivas Divriği''de 1228 yılında yaptırılan UNESCO korumasındaki şaheser.',
  '# Sivas Divriği Ulu Camii ve Darüşşifası...',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Divrigi_Ulu_Camii_Portal.jpg/1200px-Divrigi_Ulu_Camii_Portal.jpg',
  'sivas',
  'Sivas Divriği Ulu Camii ve Darüşşifası | Seni de Bekleriz',
  'Sivas Divriği Ulu Camii taç kapıları ve gölge mucizesi.',
  TRUE, NOW(), NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  cover_image = EXCLUDED.cover_image,
  city_slug = EXCLUDED.city_slug,
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  is_published = EXCLUDED.is_published,
  updated_at = NOW();
